# Numpy

__Работу выполнила: Бушуева К.Н.__    
**ПИ22-5**

## Лабораторная работа №1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [7]:
import numpy as np

from_file = np.loadtxt('minutes_n_ingredients.csv',\
                       delimiter = ',', skiprows = 1, dtype = np.int32)

print(from_file[:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [79]:
mn = from_file.mean(axis = 0)[1:]
minim = from_file.min(axis = 0)[1:]
maxim = from_file.max(axis = 0)[1:]
mediana = np.median(from_file, axis = 0)[1:]

print(mn, minim, maxim, mediana, sep = '\n')

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [224]:
q = np.quantile(from_file[:, 1:2], q = 0.75, axis = 0) 
print(from_file[from_file[:, 1] <= q])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 ...
 [ 43407     35      7]
 [498432     65     15]
 [     1      1      1]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [109]:
print(len(from_file[from_file[:, 1] == 0]))
from_file[from_file[:, 1] == 0] = 1

479


In [225]:
print(len(from_file[from_file[:, 1] == 0]))

0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [106]:
print(len(np.unique(from_file[:, 0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [230]:
print(np.unique(from_file[:, 2:]), len(np.unique(from_file[:, 2:])), sep = '\n')

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]
37


7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [43]:
print(from_file[from_file[:, 2] <= 5])

[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 ...
 [ 52088     60      5]
 [128811     15      4]
 [370915      5      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [111]:
time_ing = from_file[:, 2] / from_file[:, 1]
print(time_ing, time_ing.max(), sep = '\n')

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [81]:
sort_mas = from_file[from_file[:, 1].argsort()[::-1]][:100, :]
print(sort_mas[:, 2].mean(axis = 0))

6.61


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [127]:
lst = np.random.randint(1, 100000, size = (1, 10))
print(from_file[lst])

[[[344904     20     13]
  [316511     20     13]
  [ 84336     35      6]
  [104488     50      6]
  [ 51489     53      4]
  [ 15208     25     11]
  [ 80350     12     10]
  [171840    130      7]
  [237113    485     10]
  [ 16658      3      4]]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [128]:
av_val = from_file[:, 2].mean(axis = 0)
sum_less_av = len(from_file[from_file[:, 2] < av_val])
sum_all = from_file.shape[0]

result = sum_less_av/sum_all * 100

print(f'{result}%')

58.989000000000004%


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [217]:
new_column = np.full((100000, 1), 0)
final = np.concatenate((from_file, new_column), axis = 1)
final[:, 3] = np.where(((from_file[:, 1] <= 20) & (from_file[:, 2] <=5)), 1, 0)

print(final)

[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 ...
 [498432     65     15      0]
 [     1      1      1      1]
 [ 81993    140     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [234]:
one = np.count_nonzero(final[:, 3])
result = (one/len(final[:, 3]))*100
print(f'{result}%')

9.943%


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.